#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run generate:catalog && git add docs/component-catalog.json && npx tsc --noEmit true && npx pretty-quick --staged --pattern "**/*" --pattern "!**/*.css" --pattern "!**/*.module.css" && npx lint-staged
