name: Trigger GitLab CI Pipeline

on:
    push:
        branches:
            - main

jobs:
    trigger_pipeline:
        runs-on: ubuntu-latest

        steps:
            - name: Trigger GitLab Pipeline
              env:
                  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
                  GITLAB_ENDPOINT: ${{ vars.GITLAB_ENDPOINT }}
                  GITLAB_PROJECT_ID: ${{ vars.GITLAB_PROJECT_ID }}
                  TARGET_BRANCH: ${{ vars.GITLAB_PIPELINE_BRANCH }}
              run: |
                  curl --request POST \
                    --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
                    "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/pipeline?ref=$TARGET_BRANCH"
