name: Trigger GitLab CI Pipeline

on:
    push:
        branches:
            - master

jobs:
    trigger_pipeline:
        runs-on: ubuntu-latest

        steps:
            - name: Trigger GitLab Pipeline
              env:
                  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
                  GITLAB_ENDPOINT: ${{ vars.GITLAB_ENDPOINT }}
                  GITLAB_PROJECT_ID: ${{ vars.GITLAB_PROJECT_ID }}
                  GITLAB_REPO_NAME: ${{ vars.GITLAB_REPO_NAME }}
              run: |
                  curl --request POST \
                      --fail \ #? silences all outputs including errors
                      --form token=$GITLAB_TOKEN \
                      --form "ref=main" \
                      --form "variables[PIPELINE_PROJECT_NAME]=$GITLAB_REPO_NAME" \
                      --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/trigger/pipeline"
