name: Trigger GitLab CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Print Configs
        run: |
          [[ $GITHUB_EVENT_NAME = "pull_request" ]] && BRANCH_NAME=${{ github.head_ref }} || BRANCH_NAME=${{ github.ref_name }}

          echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_ENV"

          echo "PIPELINE_PROJECT_URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git"
          echo "PIPELINE_EVENT: $GITHUB_EVENT_NAME"
          echo "PIPELINE_BRANCH_NAME: $BRANCH_NAME"
          echo "PIPELINE_TRIGGER_PERSON: $GITHUB_ACTOR"

      - name: Trigger GitLab Pipeline
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_ENDPOINT: ${{ vars.GITLAB_ENDPOINT }}
          GITLAB_PROJECT_ID: ${{ vars.GITLAB_PROJECT_ID }}
          GITLAB_REPO_NAME: ${{ vars.GITLAB_REPO_NAME }}
        run: |
          curl -sS --request POST \
              --fail \
              --form token=$GITLAB_TOKEN \
              --form "ref=main" \
              --form "variables[PIPELINE_PROJECT_NAME]=$GITLAB_REPO_NAME" \
              --form "variables[PIPELINE_PROJECT_URL]=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" \
              --form "variables[PIPELINE_EVENT]=$GITHUB_EVENT_NAME" \
              --form "variables[PIPELINE_BRANCH_NAME]=${{ env.BRANCH_NAME }}" \
              --form "variables[PIPELINE_TRIGGER_PERSON]=$GITHUB_ACTOR" \
              --url "$GITLAB_ENDPOINT/$GITLAB_PROJECT_ID/trigger/pipeline" | jq -r '.web_url'
